# Generated by Django 5.0.14 on 2026-07-19 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_requests', '0009_baserequest_current_phase'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='passport_document',
            field=models.FileField(blank=True, null=True, upload_to='passports/'),
        ),
    ]
